apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: isvaconfig-AAC
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs.csi.aws.com
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: isvaconfig-RP
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs.csi.aws.com
  resources:
    requests:
      storage: 5Gi


      https://truststore.pki.rds.amazonaws.com/ap-southeast-1/ap-southeast-1-bundle.pem
