apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: isvd-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 300Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: isvaconfig-aac
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: isvaconfig-rp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs
  resources:
    requests:
      storage: 50Gi
