apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: isvd-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
