apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: isvd-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs
  resources:
    requests:
      storage: 45Gi
  storageClassName: standard
