apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: isvd-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
